##############################

##Author Name: Conor Cremin
##Title:Differential Expression Template

#Requirements:

#Countdata: 
#This is the raw count dataFRAME acquired from count files generated by STAR. 
#Each column of dataframe corressponds to a sample with sample ids as column headings. 
#Genes are the rows with a unique gene id as the row names. 

#Metadata:
#A file which contains the sample descriptions. File must contain at least 2 columns; "Run" is the unique sample id, 
#for SRA data this could be the SRR ids. The "Condition" column has the descriptions of samples e.g. Infected/Uninfected, this
#column must contain the components identifying the specific samples to contrast in differential expression.

##############################
#Packages:
if( !require("gplots")){
  BiocManager::install("gplots")
}
if( !require("dplyr")){
  BiocManager::install("dplyr")
}
if( !require("ggplot2")){
  BiocManager::install("ggplot2")
}
if( !require("DESeq2")){
  BiocManager::install("DESeq2")
}
if( !require("RColorBrewer")){
  BiocManager::install("RColorBrewer")
}
if( !require("limma")){
  BiocManager::install("limma")
}
if( !require("pheatmap")){
  BiocManager::install("pheatmap")
}
if( !require("gridExtra")){
  BiocManager::install("gridExtra")
}
if( !require("grid")){
  BiocManager::install("grid")
}
if( !require("ggplotify")){
  BiocManager::install("ggplotify")
}
if( !require("EnhancedVolcano")){
  BiocManager::install("EnhancedVolcano")
}

countdata <- read.table("/path/to/file")  #Specify path
metadata <- read.table("/path/to/file") #Specify path

keep <- rowSums(countdata) > 10  #Filter out genes with low counts
countdata <- countdata[keep,]

#Quality Control Check (Matching sample ids):

all(metadata$Run == colnames(countdata))

#DE- Using DESeq2

dds <- DESeqDataSetFromMatrix(countData = countdata, 
                                  colData = metadata, design = ~ Condition)
dds <-DESeq(dds)

#Variance stabilizing transformation:

vsd <- vst(dds, blind = TRUE) 

#PCA Plot

pdf("PCAplot.pdf", height=7, width=11)
plotPCA(vsd, intgroup = "Condition")
dev.off()

#Results:

res <- results(dds_all, contrast = c("Condition", "Infected", "Uninfected"), pAdjustMethod = "BH")
res <- na.omit(res, cols = c("log2FoldChange", "padj"))

#Volplot:

EnhancedVolcano(res,
                lab = rownames(res),
                x = 'log2FoldChange',
                y = 'pvalue',
                xlim = c(-5, 9),
                ylim = c(0, 100),
                pCutoff = 0.05,
                FCcutoff = 1.5,
                title = "HKUStudy",
                transcriptPointSize = 1.5,
                transcriptLabSize = 3.0,
                col=c('black', 'green3', 'blue', 'red3'),
                colAlpha = 1,
                border = 'full',
                legendPosition = "bottom")

save(res,dds, file = "Study.DE.Rdata")  #Save deseq2 object as an rdata file so it can be read in directly for meta-analysis
